---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# dwelch

<!-- badges: start -->
<!-- badges: end -->

<tt> dwelch </tt> provides code to calculate the debiased Welch estimator developed in LINK.

## Installation

You can install the development version of <tt> dwelch </tt> from [GitHub](https://github.com/) with:

``` r
devtools::install_github("astfalckl/dwelch")
```

## AR(4) Example

We demonstrate the basic functionality of <tt> dwelch </tt> with the classic AR(4) problem.

```{r example}
library(dwelch)
library(ggplot2)
library(tidyverse)
library(gsignal)

theme_set(theme_bw())

m <- 34
l <- 1111
s <- ceiling(l / 2)
n <- (m - 1) * s + l

phis <- c(2.7607, -3.8106, 2.6535, -0.9238)
sd <- 1
sampled_ar <- stats::arima.sim(list(ar = phis), n, n.start = 1000)

h <- rep(1, l)

welch_estimate <- dwelch::pwelch(sampled_ar, m, l, s, window = h)

welch_estimate %>%
    mutate(ar = ar_spectrum(welch_estimate$ff, phis, sd)) %>%
    ggplot() +
        geom_line(aes(x = ff, y = ar), colour = "#e17c1d") +
        geom_line(aes(x = ff, y = welch)) +
        scale_x_continuous(
            limits = c(0, 0.5),
            expand = c(0, 0)
        ) +
        scale_y_continuous(
            limits = c(1e-3, 1e5),
            expand = c(0, 0),
            trans = "log10"
        )

```
